env:
  - CGO_ENABLED=0
  - GO111MODULE=on

snapshot:
  name_template: "{{ .Version }}-next"

report_sizes: true

builds:
  - main: ./cmd
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X "github.com/starudream/go-lib/core/v2/config/version.gitVersion=v{{ .Version }}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  target_commitish: "{{ .Commit }}"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: Performance Improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 30
    - title: Styles
      regexp: "^.*style[(\\w)]*:+.*$"
      order: 50
    - title: Miscellaneous Chores
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 60
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 80
    - title: Dependencies
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 85
    - title: Build System
      regexp: "^.*build[(\\w)]*:+.*$"
      order: 90
    - title: Continuous Integration
      regexp: "^.*ci[(\\w)]*:+.*$"
      order: 95
    - title: Others
      order: 99
